---
local_db: sqlite3:/var/vcap/services/mewmemcached/mewmemcached_node.db
mbus: nats://localhost:4222
index: 0
base_dir: /var/vcap/services/mewmemcached/instances
ip_route: 127.0.0.1
logging:
  level: debug
pid: /var/vcap/sys/run/mewmemcached_node.pid
available_memory: 4096
max_memory: 16
max_swap: 32
node_id: mewmemcached_node_1
mewmemcached_server_path: ruby logservlauncher.rb
port_range:
  first:5000
  last: 5100
migration_nfs: /mnt/appcloud
# z_interval: 30
